#!/bin/bash
# Sample init script for the scull driver module <rubini@linux.it>

module1="faulty"
module2="hello"
# Use the same name for the device as the name used for the module
device1="faulty"
device2="hello"
# Support read/write for owner and group, read only for everyone using 644
mode="664"

set -e
# Group: since distributions do it differently, look for wheel or use staff
# These are groups which correspond to system administrator accounts
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

case "$1" in
  start)
     echo "Load our module, exit on failure"
     insmod /lib/modules/*/extra/$module1.ko || exit 1
     insmod /lib/modules/*/extra/$module2.ko || exit 1
     echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
     major=$(awk "\$2==\"$module1\" {print \$1}" /proc/devices)
     if [ ! -z ${major} ]; then
         echo "Remove any existing /dev node for /dev/${device1}"
         rm -f /dev/${device1}
         echo "Add a node for our device at /dev/${device1} using mknod"
         mknod /dev/${device1} c $major 0
         echo "Change group owner to ${group}"
         chgrp $group /dev/${device1}
         echo "Change access mode to ${mode}"
         chmod $mode  /dev/${device1}
     else
         echo "No device found in /proc/devices for driver ${module1} (this driver may not allocate a device)"
     fi
     ;;
  stop)
     # invoke rmmod with all arguments we got
     rmmod $module1 || exit 1
     rmmod $module2 || exit 1
     # Remove stale nodes
     rm -f /dev/${device1}
     rm -f /dev/${device2}
     ;;
  *)
     echo "Usage: $0 {start|stop|restart|force-reload}"
     exit 1
esac

exit 0
