#!/bin/bash
module=aesdchar
device=aesdchar
mode="664"
cd `dirname $0`
set -e
# Group: since distributions do it differently, look for wheel or use staff
# These are groups which correspond to system administrator accounts
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

case "$1" in
  start)
     echo "Loading local built file ${module}.ko"
     insmod /lib/modules/*/extra/$module.ko || exit 1
    
     major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
     if [ ! -z ${major} ]; then
         echo "Remove any existing /dev node for /dev/${device}"
         rm -f /dev/${device}
         echo "Add a node for our device at /dev/${device} using mknod"
         mknod /dev/${device} c $major 0
         echo "Change group owner to ${group}"
         chgrp $group /dev/${device}
         echo "Change access mode to ${mode}"
         chmod $mode  /dev/${device}
     else
         echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
     fi
     ;;
  stop)
     # invoke rmmod with all arguments we got
     rmmod $module || exit 1

     # Remove stale nodes
     rm -f /dev/${device}
     ;;
  *)
     echo "Usage: $0 {start|stop}"
     exit 1
esac

exit 0
